from database.db import SessionLocal, create_tables
from models.models import Question, CompanyQuestion

COMMUNICATION_TOPICS = [
    "Tell me about yourself",
    "Why do you want to work in the IT industry?",
    "What are your strengths and weaknesses?",
    "Describe a challenging situation you faced and how you handled it",
    "Where do you see yourself in 5 years?",
    "Why should we hire you?",
    "Describe your final year project",
    "What motivates you to work hard?",
    "How do you handle pressure and tight deadlines?",
    "What do you know about our company?",
]

QUANT = [
    {"category": "quantitative", "difficulty": "easy", "question_text": "A train travels 360 km in 4 hours. What is its speed in km/h?", "options": ["80", "90", "100", "110"], "correct_answer": "90", "explanation": "Speed = Distance / Time = 360 / 4 = 90 km/h", "tags": ["speed-distance-time"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "A car covers 288 km in 4 hours. How far will it travel in 6.5 hours at the same speed?", "options": ["432 km", "450 km", "468 km", "480 km"], "correct_answer": "468 km", "explanation": "Speed = 72 km/h. Distance = 72 × 6.5 = 468 km", "tags": ["speed-distance-time"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "Shopkeeper sells at 20% profit. Cost price = ₹500. Selling price?", "options": ["₹550", "₹580", "₹600", "₹620"], "correct_answer": "₹600", "explanation": "SP = CP × 1.20 = 500 × 1.20 = ₹600", "tags": ["profit-loss"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Item bought for ₹800, sold at ₹680. Loss percentage?", "options": ["12%", "15%", "17%", "20%"], "correct_answer": "15%", "explanation": "Loss = 120. Loss% = 120/800 × 100 = 15%", "tags": ["profit-loss"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "What is 15% of 480?", "options": ["62", "68", "72", "75"], "correct_answer": "72", "explanation": "15% of 480 = 480 × 15/100 = 72", "tags": ["percentages"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Price increased by 20% then decreased by 20%. Net change?", "options": ["-4%", "0%", "+4%", "-2%"], "correct_answer": "-4%", "explanation": "100 → 120 → 96. Net = -4%", "tags": ["percentages"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "30% of what number is 90?", "options": ["270", "280", "300", "320"], "correct_answer": "300", "explanation": "x × 30/100 = 90 → x = 300", "tags": ["percentages"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "Simple interest on ₹8000 at 5% per annum for 3 years?", "options": ["₹1000", "₹1100", "₹1200", "₹1300"], "correct_answer": "₹1200", "explanation": "SI = PRT/100 = 8000×5×3/100 = ₹1200", "tags": ["simple-interest"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "A sum doubles in 10 years at simple interest. Rate of interest?", "options": ["8%", "9%", "10%", "12%"], "correct_answer": "10%", "explanation": "P = P×R×10/100 → R = 10%", "tags": ["simple-interest"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Compound interest on ₹10000 at 10% per annum for 2 years?", "options": ["₹2000", "₹2100", "₹2200", "₹2500"], "correct_answer": "₹2100", "explanation": "CI = 10000[(1.1)² - 1] = ₹2100", "tags": ["compound-interest"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "6 workers complete a job in 8 days. How many workers to finish in 3 days?", "options": ["14", "16", "18", "20"], "correct_answer": "16", "explanation": "6 × 8 = x × 3 → x = 16", "tags": ["work-time"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "A can do work in 10 days, B in 15 days. Together?", "options": ["5 days", "6 days", "7 days", "8 days"], "correct_answer": "6 days", "explanation": "Combined rate = 1/10 + 1/15 = 1/6. Time = 6 days", "tags": ["work-time"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Pipes A and B fill a tank in 12 and 16 hours. Both opened together. Time?", "options": ["6.5 hr", "6.86 hr", "7 hr", "7.5 hr"], "correct_answer": "6.86 hr", "explanation": "1/12 + 1/16 = 7/48. Time = 48/7 ≈ 6.86 hr", "tags": ["pipes-cisterns"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "Ratio A:B = 3:5. If B = 45, find A?", "options": ["25", "27", "30", "32"], "correct_answer": "27", "explanation": "A/45 = 3/5 → A = 27", "tags": ["ratio-proportion"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "₹600 divided in ratio 1:2:3. Largest share?", "options": ["₹250", "₹280", "₹300", "₹320"], "correct_answer": "₹300", "explanation": "Largest = 3/6 × 600 = ₹300", "tags": ["ratio-proportion"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "Average of 5 numbers is 27. Excluding one, average is 25. Excluded number?", "options": ["30", "33", "35", "37"], "correct_answer": "35", "explanation": "Sum of 5 = 135. Sum of 4 = 100. Excluded = 35", "tags": ["averages"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Average of 10 numbers = 20. Each multiplied by 3. New average?", "options": ["23", "40", "60", "80"], "correct_answer": "60", "explanation": "Average triples = 20 × 3 = 60", "tags": ["averages"]},
    {"category": "quantitative", "difficulty": "hard", "question_text": "Average age of 30 students = 14. Teacher joins, avg becomes 15. Teacher's age?", "options": ["40", "41", "44", "45"], "correct_answer": "45", "explanation": "30×14 = 420. 31×15 = 465. Teacher = 465 - 420 = 45", "tags": ["averages"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Boat speed 15 km/h, stream speed 3 km/h. Upstream speed?", "options": ["10", "12", "13", "18"], "correct_answer": "12", "explanation": "Upstream = 15 - 3 = 12 km/h", "tags": ["boats-streams"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "LCM of 12 and 18?", "options": ["24", "36", "48", "72"], "correct_answer": "36", "explanation": "LCM(12, 18) = 36", "tags": ["number-system"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "HCF of 144, 198, and 36?", "options": ["6", "9", "12", "18"], "correct_answer": "18", "explanation": "HCF(144, 198, 36) = 18", "tags": ["number-system"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "Sum of first 50 natural numbers?", "options": ["1225", "1275", "1325", "1375"], "correct_answer": "1275", "explanation": "n(n+1)/2 = 50×51/2 = 1275", "tags": ["number-system"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "Area of circle with radius 7 cm? (π = 22/7)", "options": ["150 cm²", "154 cm²", "158 cm²", "162 cm²"], "correct_answer": "154 cm²", "explanation": "A = πr² = 22/7 × 49 = 154 cm²", "tags": ["mensuration"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Volume of cylinder r = 7cm, h = 10cm? (π = 22/7)", "options": ["1450", "1540", "1630", "1720"], "correct_answer": "1540", "explanation": "V = πr²h = 22/7 × 49 × 10 = 1540 cm³", "tags": ["mensuration"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "Perimeter of rectangle l = 12cm, b = 8cm?", "options": ["36cm", "40cm", "42cm", "48cm"], "correct_answer": "40cm", "explanation": "P = 2(l+b) = 2(12+8) = 40 cm", "tags": ["mensuration"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "A die is thrown. Probability of getting a prime number?", "options": ["1/2", "1/3", "2/3", "1/6"], "correct_answer": "1/2", "explanation": "Primes on a die: 2, 3, 5. P = 3/6 = 1/2", "tags": ["probability"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Bag has 5 red, 3 blue, 2 green balls. P(red)?", "options": ["1/2", "3/10", "1/3", "2/5"], "correct_answer": "1/2", "explanation": "P(red) = 5/10 = 1/2", "tags": ["probability"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "How many ways can 5 people be arranged in a row?", "options": ["60", "100", "120", "240"], "correct_answer": "120", "explanation": "5! = 120", "tags": ["permutation-combination"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Select committee of 3 from 8 people. How many ways?", "options": ["56", "112", "168", "336"], "correct_answer": "56", "explanation": "C(8,3) = 8! / (3! × 5!) = 56", "tags": ["permutation-combination"]},
    {"category": "quantitative", "difficulty": "easy", "question_text": "If 3x + 7 = 22, find x?", "options": ["4", "5", "6", "7"], "correct_answer": "5", "explanation": "3x = 15 → x = 5", "tags": ["algebra"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "If x² - 5x + 6 = 0, values of x?", "options": ["2 and 3", "1 and 6", "2 and 4", "3 and 4"], "correct_answer": "2 and 3", "explanation": "(x-2)(x-3) = 0 → x = 2 or 3", "tags": ["algebra"]},
    {"category": "quantitative", "difficulty": "hard", "question_text": "Pipe A fills tank in 30 min, pipe B empties in 40 min. Both open. Time to fill?", "options": ["100 min", "110 min", "120 min", "130 min"], "correct_answer": "120 min", "explanation": "Net rate = 1/30 - 1/40 = 1/120. Time = 120 min", "tags": ["pipes-cisterns"]},
    {"category": "quantitative", "difficulty": "medium", "question_text": "Angle between hour and minute hands at 3:30?", "options": ["60°", "65°", "75°", "80°"], "correct_answer": "75°", "explanation": "Hour at 105°, minute at 180°. Difference = 75°", "tags": ["clocks"]},
    {"category": "quantitative", "difficulty": "hard", "question_text": "How many times do clock hands coincide in 12 hours?", "options": ["10", "11", "12", "13"], "correct_answer": "11", "explanation": "Hands coincide 11 times in 12 hours", "tags": ["clocks"]},
    {"category": "quantitative", "difficulty": "hard", "question_text": "A sells to B at 10% profit, B sells to C at 10% profit. C pays ₹121. A's cost price?", "options": ["₹90", "₹95", "₹100", "₹110"], "correct_answer": "₹100", "explanation": "CP × 1.1 × 1.1 = 121 → CP = 100", "tags": ["profit-loss"]},
    {"category": "quantitative", "difficulty": "hard", "question_text": "Difference between CI and SI on ₹5000 at 8% for 2 years?", "options": ["₹28", "₹32", "₹40", "₹50"], "correct_answer": "₹32", "explanation": "SI=800, CI=832. Difference = 32", "tags": ["compound-interest"]},
]

LOGICAL = [
    {"category": "logical", "difficulty": "easy", "question_text": "2, 6, 12, 20, 30, ?", "options": ["40", "42", "44", "46"], "correct_answer": "42", "explanation": "Differences: 4,6,8,10,12. Next = 30 + 12 = 42", "tags": ["number-series"]},
    {"category": "logical", "difficulty": "easy", "question_text": "1, 4, 9, 16, 25, ?", "options": ["30", "36", "42", "49"], "correct_answer": "36", "explanation": "Perfect squares: 1²,2²,3²... 6² = 36", "tags": ["number-series"]},
    {"category": "logical", "difficulty": "medium", "question_text": "3, 9, 27, 81, ?", "options": ["162", "243", "324", "189"], "correct_answer": "243", "explanation": "Each × 3. 81 × 3 = 243", "tags": ["number-series"]},
    {"category": "logical", "difficulty": "medium", "question_text": "1, 1, 2, 3, 5, 8, 13, ?", "options": ["19", "20", "21", "22"], "correct_answer": "21", "explanation": "Fibonacci: 8 + 13 = 21", "tags": ["number-series"]},
    {"category": "logical", "difficulty": "hard", "question_text": "2, 3, 5, 9, 17, 33, ?", "options": ["60", "65", "67", "70"], "correct_answer": "65", "explanation": "Each = previous × 2 - 1. 33 × 2 - 1 = 65", "tags": ["number-series"]},
    {"category": "logical", "difficulty": "easy", "question_text": "100, 96, 88, 72, ?", "options": ["40", "42", "44", "56"], "correct_answer": "40", "explanation": "Differences double: 4,8,16,32. 72 - 32 = 40", "tags": ["number-series"]},
    {"category": "logical", "difficulty": "hard", "question_text": "1, 2, 6, 24, 120, ?", "options": ["360", "480", "720", "840"], "correct_answer": "720", "explanation": "Factorial series: 1!,2!,3!,4!,5!,6! = 720", "tags": ["number-series"]},
    {"category": "logical", "difficulty": "easy", "question_text": "Find odd one out: 2, 3, 5, 7, 9, 11", "options": ["2", "9", "11", "5"], "correct_answer": "9", "explanation": "9 = 3×3, not prime. All others are prime", "tags": ["odd-one-out"]},
    {"category": "logical", "difficulty": "easy", "question_text": "Odd one out: Apple, Mango, Banana, Potato, Orange", "options": ["Apple", "Banana", "Potato", "Orange"], "correct_answer": "Potato", "explanation": "Potato is a vegetable; others are fruits", "tags": ["odd-one-out"]},
    {"category": "logical", "difficulty": "medium", "question_text": "Odd one out: 121, 169, 196, 225, 290", "options": ["121", "196", "225", "290"], "correct_answer": "290", "explanation": "All others are perfect squares. 290 is not", "tags": ["odd-one-out"]},
    {"category": "logical", "difficulty": "easy", "question_text": "All roses are flowers. All flowers are plants. All roses are plants?", "options": ["True", "False", "Uncertain", "Cannot determine"], "correct_answer": "True", "explanation": "Transitive: roses → flowers → plants", "tags": ["syllogisms"]},
    {"category": "logical", "difficulty": "medium", "question_text": "Some cats are dogs. All dogs are animals. Which is definitely true?", "options": ["All cats are animals", "Some cats are animals", "All animals are dogs", "No cats are animals"], "correct_answer": "Some cats are animals", "explanation": "Some cats → dogs → animals", "tags": ["syllogisms"]},
    {"category": "logical", "difficulty": "hard", "question_text": "No manager is a worker. Some workers are graduates. Which conclusion follows?", "options": ["No graduate is a manager", "Some graduates are not managers", "All graduates are managers", "Some managers are graduates"], "correct_answer": "Some graduates are not managers", "explanation": "Some workers (graduates) are not managers", "tags": ["syllogisms"]},
    {"category": "logical", "difficulty": "easy", "question_text": "A is B's sister. C is B's mother. D is C's father. How is A related to D?", "options": ["Granddaughter", "Daughter", "Grandmother", "Niece"], "correct_answer": "Granddaughter", "explanation": "D is A's grandfather, so A is his granddaughter", "tags": ["blood-relations"]},
    {"category": "logical", "difficulty": "medium", "question_text": "Pointing to a man, woman says 'His mother is only daughter of my mother'. Woman is?", "options": ["Mother", "Daughter", "Sister", "Grandmother"], "correct_answer": "Mother", "explanation": "Only daughter of woman's mother = the woman herself", "tags": ["blood-relations"]},
    {"category": "logical", "difficulty": "easy", "question_text": "In a row of 40, Priya is 11th from left. Position from right?", "options": ["28th", "29th", "30th", "31st"], "correct_answer": "30th", "explanation": "40 - 11 + 1 = 30", "tags": ["ranking"]},
    {"category": "logical", "difficulty": "medium", "question_text": "Ravi is 7th from left and 8th from right. Total in row?", "options": ["13", "14", "15", "16"], "correct_answer": "14", "explanation": "Total = 7 + 8 - 1 = 14", "tags": ["ranking"]},
    {"category": "logical", "difficulty": "easy", "question_text": "Ram walks 5km North, right 3km, right 5km. How far from start?", "options": ["3km East", "3km West", "3km North", "3km South"], "correct_answer": "3km East", "explanation": "N5, E3, S5 → net = 3km East of start", "tags": ["direction-sense"]},
    {"category": "logical", "difficulty": "medium", "question_text": "A faces East, turns 90° clockwise, then 180°. Direction now?", "options": ["North", "South", "East", "West"], "correct_answer": "North", "explanation": "East → South (90°CW) → North (180°)", "tags": ["direction-sense"]},
    {"category": "logical", "difficulty": "easy", "question_text": "If MANGO is coded as OCPIQ, how is APPLE coded?", "options": ["CRRNG", "CRQNG", "CRROF", "DSSOH"], "correct_answer": "CRRNG", "explanation": "Each letter + 2. A→C, P→R, P→R, L→N, E→G", "tags": ["coding-decoding"]},
    {"category": "logical", "difficulty": "medium", "question_text": "Complete pattern: AZ, BY, CX, DW, ?", "options": ["EV", "EU", "FV", "EW"], "correct_answer": "EV", "explanation": "Forward + backward alphabet: E, V", "tags": ["pattern"]},
    {"category": "logical", "difficulty": "hard", "question_text": "Matrix: 2,4,8 | 3,9,27 | 4,16,? What is ?", "options": ["32", "48", "64", "128"], "correct_answer": "64", "explanation": "n, n², n³. Row 3: 4, 16, 64", "tags": ["pattern"]},
    {"category": "logical", "difficulty": "easy", "question_text": "Book : Library :: Painting : ?", "options": ["Artist", "Canvas", "Gallery", "Museum"], "correct_answer": "Gallery", "explanation": "Books are kept in Library; Paintings in Gallery", "tags": ["analogies"]},
    {"category": "logical", "difficulty": "easy", "question_text": "Doctor : Hospital :: Teacher : ?", "options": ["Study", "School", "Student", "Classroom"], "correct_answer": "School", "explanation": "Doctor works in Hospital; Teacher works in School", "tags": ["analogies"]},
    {"category": "logical", "difficulty": "medium", "question_text": "ACEG : BDFH :: PRTV : ?", "options": ["QSUW", "QSTU", "RSUW", "QRST"], "correct_answer": "QSUW", "explanation": "Add 1 to each letter", "tags": ["analogies"]},
    {"category": "logical", "difficulty": "hard", "question_text": "If P implies Q and Q implies R, which must be true?", "options": ["R implies P", "P implies R", "Q implies P", "R implies Q"], "correct_answer": "P implies R", "explanation": "P→Q→R, so P→R by transitivity", "tags": ["critical-reasoning"]},
    {"category": "logical", "difficulty": "medium", "question_text": "All employees who worked overtime got bonus. Ravi didn't get bonus. Therefore?", "options": ["Ravi worked overtime", "Ravi didn't work overtime", "Ravi not eligible", "Ravi was absent"], "correct_answer": "Ravi didn't work overtime", "explanation": "Contrapositive: no bonus → didn't work overtime", "tags": ["critical-reasoning"]},
    {"category": "logical", "difficulty": "medium", "question_text": "Statement: All politicians are corrupt. Ram is a politician. Conclusion: Ram is corrupt.", "options": ["Follows", "Does not follow", "Partially follows", "Cannot determine"], "correct_answer": "Follows", "explanation": "Based on given statements, conclusion logically follows", "tags": ["statement-conclusion"]},
    {"category": "logical", "difficulty": "hard", "question_text": "Some chairs are tables. All tables wooden. Conclusion 1: Some chairs wooden. Conclusion 2: All wooden are chairs.", "options": ["Only 1 follows", "Only 2 follows", "Both follow", "Neither follows"], "correct_answer": "Only 1 follows", "explanation": "Some chairs→tables→wooden. Not all wooden are chairs", "tags": ["statement-conclusion"]},
    {"category": "logical", "difficulty": "easy", "question_text": "7, 14, 28, 56, ?", "options": ["96", "100", "112", "120"], "correct_answer": "112", "explanation": "Each × 2. 56 × 2 = 112", "tags": ["number-series"]},
    {"category": "logical", "difficulty": "medium", "question_text": "Ravi is 16th from top in class of 40. Rank from bottom?", "options": ["23", "24", "25", "26"], "correct_answer": "25", "explanation": "40 - 16 + 1 = 25", "tags": ["ranking"]},
    {"category": "logical", "difficulty": "medium", "question_text": "Angle between hour and minute hands at 4:20?", "options": ["0°", "5°", "10°", "15°"], "correct_answer": "10°", "explanation": "Minute = 120°. Hour = 130°. Difference = 10°", "tags": ["clocks"]},
    {"category": "logical", "difficulty": "easy", "question_text": "COLD : WARM as NIGHT : ?", "options": ["Dark", "Day", "Moon", "Stars"], "correct_answer": "Day", "explanation": "COLD and WARM are opposites; NIGHT opposite is DAY", "tags": ["analogies"]},
    {"category": "logical", "difficulty": "easy", "question_text": "Odd one out: Pen, Pencil, Eraser, Sharpener, Book", "options": ["Pen", "Pencil", "Book", "Eraser"], "correct_answer": "Book", "explanation": "All others are writing/drawing instruments", "tags": ["odd-one-out"]},
    {"category": "logical", "difficulty": "medium", "question_text": "A is father of C. B is mother of D. C and D are siblings. A related to B?", "options": ["Father", "Husband", "Brother", "Uncle"], "correct_answer": "Husband", "explanation": "A(father) and B(mother) have same children, so A is B's husband", "tags": ["blood-relations"]},
]

CODING = [
    {"category": "coding", "difficulty": "easy", "question_text": "## Reverse a String\nReturn the reverse of the input string.\n\n**Input:** `hello`\n**Output:** `olleh`", "correct_answer": "", "starter_code": "s = input()\n\ndef reverse_string(s):\n    # Your code here\n    pass\n\nprint(reverse_string(s))", "test_cases": [{"input": "hello", "expected": "olleh"}, {"input": "placement", "expected": "tnemecalp"}, {"input": "abcde", "expected": "edcba"}, {"input": "a", "expected": "a"}], "tags": ["strings", "easy"]},
    {"category": "coding", "difficulty": "easy", "question_text": "## Check Palindrome\nPrint `True` if string is palindrome, else `False`.\n\n**Input:** `racecar`\n**Output:** `True`", "correct_answer": "", "starter_code": "s = input().strip()\n\ndef is_palindrome(s):\n    # Your code here\n    pass\n\nprint(is_palindrome(s))", "test_cases": [{"input": "racecar", "expected": "True"}, {"input": "hello", "expected": "False"}, {"input": "madam", "expected": "True"}, {"input": "python", "expected": "False"}], "tags": ["strings", "easy"]},
    {"category": "coding", "difficulty": "easy", "question_text": "## Sum of Digits\nFind sum of all digits of number N.\n\n**Input:** `123`\n**Output:** `6`", "correct_answer": "", "starter_code": "n = input().strip()\n\ndef sum_of_digits(n):\n    # Your code here\n    pass\n\nprint(sum_of_digits(n))", "test_cases": [{"input": "123", "expected": "6"}, {"input": "9999", "expected": "36"}, {"input": "0", "expected": "0"}, {"input": "100", "expected": "1"}], "tags": ["math", "easy"]},
    {"category": "coding", "difficulty": "easy", "question_text": "## Count Vowels\nCount vowels (a,e,i,o,u) case-insensitive.\n\n**Input:** `Hello World`\n**Output:** `3`", "correct_answer": "", "starter_code": "s = input()\n\ndef count_vowels(s):\n    # Your code here\n    pass\n\nprint(count_vowels(s))", "test_cases": [{"input": "Hello World", "expected": "3"}, {"input": "Python", "expected": "1"}, {"input": "AEIOU", "expected": "5"}, {"input": "xyz", "expected": "0"}], "tags": ["strings", "easy"]},
    {"category": "coding", "difficulty": "medium", "question_text": "## Factorial\nFind factorial of N.\n\n**Input:** `5`\n**Output:** `120`", "correct_answer": "", "starter_code": "n = int(input())\n\ndef factorial(n):\n    # Your code here\n    pass\n\nprint(factorial(n))", "test_cases": [{"input": "5", "expected": "120"}, {"input": "0", "expected": "1"}, {"input": "10", "expected": "3628800"}, {"input": "1", "expected": "1"}], "tags": ["recursion", "medium"]},
    {"category": "coding", "difficulty": "medium", "question_text": "## Fibonacci Series\nPrint first N Fibonacci numbers space-separated.\n\n**Input:** `7`\n**Output:** `0 1 1 2 3 5 8`", "correct_answer": "", "starter_code": "n = int(input())\n\ndef fibonacci(n):\n    # Your code here\n    pass\n\nprint(*fibonacci(n))", "test_cases": [{"input": "7", "expected": "0 1 1 2 3 5 8"}, {"input": "1", "expected": "0"}, {"input": "5", "expected": "0 1 1 2 3"}, {"input": "2", "expected": "0 1"}], "tags": ["dp", "medium"]},
    {"category": "coding", "difficulty": "medium", "question_text": "## Two Sum\nFind indices of two numbers adding to target.\n\nLine 1: space-separated integers\nLine 2: target\n\n**Input:** `2 7 11 15` / `9`\n**Output:** `0 1`", "correct_answer": "", "starter_code": "nums = list(map(int, input().split()))\ntarget = int(input())\n\ndef two_sum(nums, target):\n    # Your code here\n    pass\n\nr = two_sum(nums, target)\nprint(r[0], r[1])", "test_cases": [{"input": "2 7 11 15\n9", "expected": "0 1"}, {"input": "3 2 4\n6", "expected": "1 2"}], "tags": ["arrays", "medium"]},
    {"category": "coding", "difficulty": "medium", "question_text": "## Prime Check\nCheck if N is prime. Print `True` or `False`.\n\n**Input:** `17`\n**Output:** `True`", "correct_answer": "", "starter_code": "n = int(input())\n\ndef is_prime(n):\n    # Your code here\n    pass\n\nprint(is_prime(n))", "test_cases": [{"input": "17", "expected": "True"}, {"input": "4", "expected": "False"}, {"input": "2", "expected": "True"}, {"input": "1", "expected": "False"}], "tags": ["math", "medium"]},
    {"category": "coding", "difficulty": "medium", "question_text": "## Find Duplicates\nFind all duplicate numbers. Print sorted space-separated. If none print `None`.\n\n**Input:** `4 3 2 7 8 2 3 1`\n**Output:** `2 3`", "correct_answer": "", "starter_code": "nums = list(map(int, input().split()))\n\ndef find_duplicates(nums):\n    # Your code here\n    pass\n\nresult = find_duplicates(nums)\nif result:\n    print(*sorted(result))\nelse:\n    print('None')", "test_cases": [{"input": "4 3 2 7 8 2 3 1", "expected": "2 3"}, {"input": "1 2 3", "expected": "None"}, {"input": "1 1 2 2 3 3", "expected": "1 2 3"}], "tags": ["arrays", "medium"]},
    {"category": "coding", "difficulty": "hard", "question_text": "## Binary Search\nReturn index if found, -1 if not.\n\nLine 1: sorted integers, Line 2: target\n\n**Input:** `1 3 5 7 9` / `7`\n**Output:** `3`", "correct_answer": "", "starter_code": "arr = list(map(int, input().split()))\ntarget = int(input())\n\ndef binary_search(arr, target):\n    # Your code here\n    pass\n\nprint(binary_search(arr, target))", "test_cases": [{"input": "1 3 5 7 9\n7", "expected": "3"}, {"input": "1 3 5 7 9\n6", "expected": "-1"}, {"input": "2 4 6 8\n2", "expected": "0"}], "tags": ["searching", "hard"]},
    {"category": "coding", "difficulty": "hard", "question_text": "## Anagram Check\nCheck if two strings are anagrams. Print `True` or `False`.\n\nLine 1: first string, Line 2: second string\n\n**Input:** `listen` / `silent`\n**Output:** `True`", "correct_answer": "", "starter_code": "s1 = input().strip().lower()\ns2 = input().strip().lower()\n\ndef is_anagram(s1, s2):\n    # Your code here\n    pass\n\nprint(is_anagram(s1, s2))", "test_cases": [{"input": "listen\nsilent", "expected": "True"}, {"input": "hello\nworld", "expected": "False"}, {"input": "triangle\nintegral", "expected": "True"}], "tags": ["strings", "hard"]},
    {"category": "coding", "difficulty": "hard", "question_text": "## Maximum Subarray (Kadane's Algorithm)\nFind maximum sum of a contiguous subarray.\n\n**Input:** `-2 1 -3 4 -1 2 1 -5 4`\n**Output:** `6`", "correct_answer": "", "starter_code": "nums = list(map(int, input().split()))\n\ndef max_subarray(nums):\n    # Your code here\n    pass\n\nprint(max_subarray(nums))", "test_cases": [{"input": "-2 1 -3 4 -1 2 1 -5 4", "expected": "6"}, {"input": "1", "expected": "1"}, {"input": "-1 -2 -3", "expected": "-1"}], "tags": ["dp", "hard"]},
    {"category": "coding", "difficulty": "medium", "question_text": "## Second Largest\nFind the second largest number in a list.\n\n**Input:** `12 35 1 10 34 1`\n**Output:** `34`", "correct_answer": "", "starter_code": "nums = list(map(int, input().split()))\n\ndef second_largest(nums):\n    # Your code here\n    pass\n\nprint(second_largest(nums))", "test_cases": [{"input": "12 35 1 10 34 1", "expected": "34"}, {"input": "1 2", "expected": "1"}, {"input": "5 5 5 4", "expected": "4"}], "tags": ["arrays", "medium"]},
    {"category": "coding", "difficulty": "easy", "question_text": "## Count Words\nCount number of words in a sentence.\n\n**Input:** `Hello World how are you`\n**Output:** `5`", "correct_answer": "", "starter_code": "s = input()\n\ndef count_words(s):\n    # Your code here\n    pass\n\nprint(count_words(s))", "test_cases": [{"input": "Hello World how are you", "expected": "5"}, {"input": "Python", "expected": "1"}, {"input": "one two three four", "expected": "4"}], "tags": ["strings", "easy"]},
    {"category": "coding", "difficulty": "medium", "question_text": "## FizzBuzz\nPrint 1 to N. Multiples of 3 = Fizz, 4 = Buzz, both = FizzBuzz.\n\n**Input:** `15`\n**Output:** `1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz`", "correct_answer": "", "starter_code": "n = int(input())\n\nresult = []\nfor i in range(1, n + 1):\n    # Your code here\n    pass\n\nprint(*result)", "test_cases": [{"input": "15", "expected": "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz"}, {"input": "3", "expected": "1 2 Fizz"}], "tags": ["loops", "medium"]},
]

COMPANY_QUESTIONS = [
    {"company": "tcs", "category": "quantitative", "difficulty": "medium", "question_text": "TCS NQT: A train 250m long passes a platform 350m long in 60 seconds. Speed in km/h?", "options": ["30", "36", "40", "42"], "correct_answer": "36", "explanation": "Speed = (250+350)/60 = 10 m/s = 36 km/h", "tags": ["speed", "tcs"], "year": 2023},
    {"company": "tcs", "category": "logical", "difficulty": "medium", "question_text": "TCS: If RED = 27, GREEN = 49, then BLUE = ?", "options": ["34", "36", "40", "42"], "correct_answer": "34", "explanation": "B(2)+L(12)+U(21)-1 = 34 (pattern based)", "tags": ["coding-decoding", "tcs"], "year": 2023},
    {"company": "tcs", "category": "quantitative", "difficulty": "easy", "question_text": "TCS Digital: CI on ₹12,000 at 10% per annum for 2 years?", "options": ["₹2400", "₹2520", "₹2640", "₹2760"], "correct_answer": "₹2520", "explanation": "CI = 12000[(1.1)² - 1] = ₹2520", "tags": ["compound-interest", "tcs"], "year": 2023},
    {"company": "tcs", "category": "quantitative", "difficulty": "hard", "question_text": "TCS Ninja: A can do work in 24 days, B in 36 days. Work together 6 days, then B alone. Total days?", "options": ["21", "24", "27", "30"], "correct_answer": "27", "explanation": "Together 6 days: 5/12 done. Remaining = 7/12. B alone: 7/12 × 36 = 21. Total = 27", "tags": ["work-time", "tcs"], "year": 2023},
    {"company": "tcs", "category": "logical", "difficulty": "easy", "question_text": "TCS: Find next: 5, 10, 20, 40, ?", "options": ["60", "70", "80", "90"], "correct_answer": "80", "explanation": "Each × 2. 40 × 2 = 80", "tags": ["number-series", "tcs"], "year": 2022},
    {"company": "infosys", "category": "quantitative", "difficulty": "medium", "question_text": "Infosys: Ratio boys:girls = 3:2. If 5 more boys join, ratio becomes 2:1. Total originally?", "options": ["20", "25", "30", "35"], "correct_answer": "25", "explanation": "(3x+5)/2x = 2 → x = 5. Total = 25", "tags": ["ratio", "infosys"], "year": 2023},
    {"company": "infosys", "category": "logical", "difficulty": "medium", "question_text": "Infosys: Ravi is 15th from left, 16th from right. Total people in row?", "options": ["28", "29", "30", "31"], "correct_answer": "30", "explanation": "Total = 15 + 16 - 1 = 30", "tags": ["ranking", "infosys"], "year": 2023},
    {"company": "infosys", "category": "quantitative", "difficulty": "medium", "question_text": "Infosys: Average marks of 40 students = 80. Top 10 avg = 90, bottom 10 avg = 70. Middle 20 avg?", "options": ["78", "80", "82", "85"], "correct_answer": "80", "explanation": "Total=3200. Top=900. Bottom=700. Middle=1600/20=80", "tags": ["averages", "infosys"], "year": 2023},
    {"company": "wipro", "category": "quantitative", "difficulty": "easy", "question_text": "Wipro NLTH: Next prime after 97?", "options": ["99", "101", "103", "107"], "correct_answer": "101", "explanation": "101 is prime (not divisible by 2,3,5,7)", "tags": ["number-system", "wipro"], "year": 2023},
    {"company": "wipro", "category": "logical", "difficulty": "medium", "question_text": "Wipro: BIRD : CAGE :: CRIMINAL : ?", "options": ["Police", "Jail", "Law", "Court"], "correct_answer": "Jail", "explanation": "Bird is kept in Cage; Criminal is kept in Jail", "tags": ["analogies", "wipro"], "year": 2023},
    {"company": "wipro", "category": "quantitative", "difficulty": "medium", "question_text": "Wipro: 6 men, 10 days, 8 hrs/day. For 4 men, 9 days, hours/day?", "options": ["10", "12", "13.33", "14"], "correct_answer": "13.33", "explanation": "6×10×8 = 4×9×h → h = 480/36 = 13.33", "tags": ["work-time", "wipro"], "year": 2022},
    {"company": "zoho", "category": "quantitative", "difficulty": "hard", "question_text": "Zoho: HCF = 8, LCM = 192. One number = 64. Find the other?", "options": ["16", "24", "32", "48"], "correct_answer": "24", "explanation": "a×b = HCF×LCM = 1536. b = 1536/64 = 24", "tags": ["number-system", "zoho"], "year": 2023},
    {"company": "zoho", "category": "logical", "difficulty": "hard", "question_text": "Zoho: Some books are pens. No pen is pencil. All pencils are erasers. Some books are erasers?", "options": ["Follows", "Does not follow", "Cannot determine", "Partially follows"], "correct_answer": "Does not follow", "explanation": "No direct link books → erasers through given statements", "tags": ["syllogisms", "zoho"], "year": 2023},
    {"company": "zoho", "category": "quantitative", "difficulty": "medium", "question_text": "Zoho: log₂ x = 4, find x?", "options": ["8", "12", "16", "24"], "correct_answer": "16", "explanation": "x = 2⁴ = 16", "tags": ["algebra", "zoho"], "year": 2022},
    {"company": "accenture", "category": "quantitative", "difficulty": "easy", "question_text": "Accenture: Room 15m × 12m. Cost of carpeting at ₹35 per sq.m?", "options": ["₹6200", "₹6300", "₹6400", "₹6500"], "correct_answer": "₹6300", "explanation": "Area = 180 sq.m. Cost = 180 × 35 = ₹6300", "tags": ["mensuration", "accenture"], "year": 2023},
    {"company": "accenture", "category": "logical", "difficulty": "medium", "question_text": "Accenture: Ways to arrange letters of LEADER?", "options": ["360", "720", "1440", "2880"], "correct_answer": "360", "explanation": "6 letters, E repeated twice. 6!/2! = 360", "tags": ["permutation", "accenture"], "year": 2023},
    {"company": "accenture", "category": "quantitative", "difficulty": "medium", "question_text": "Accenture: Train 45 km/h. Seconds to cover 1 km?", "options": ["60s", "72s", "80s", "90s"], "correct_answer": "80s", "explanation": "45 km/h = 12.5 m/s. 1000/12.5 = 80s", "tags": ["speed", "accenture"], "year": 2022},
    {"company": "cognizant", "category": "quantitative", "difficulty": "medium", "question_text": "CTS: Pipe fills in 20 min, another empties in 30 min. Both open. Time to fill?", "options": ["50 min", "55 min", "60 min", "65 min"], "correct_answer": "60 min", "explanation": "Net rate = 1/20 - 1/30 = 1/60. Time = 60 min", "tags": ["pipes", "cognizant"], "year": 2023},
    {"company": "cognizant", "category": "quantitative", "difficulty": "hard", "question_text": "CTS: Sum at CI becomes ₹1200 in 2 years, ₹1440 in 4 years. Find principal.", "options": ["₹800", "₹900", "₹1000", "₹1100"], "correct_answer": "₹1000", "explanation": "1440/1200 = 1.2 = (1+r)². P = 1200/1.2 = 1000", "tags": ["compound-interest", "cognizant"], "year": 2022},
    {"company": "hcl", "category": "quantitative", "difficulty": "medium", "question_text": "HCL: A does work in 15 days, B in 20, C in 30. All three together?", "options": ["5 days", "6 days", "7 days", "8 days"], "correct_answer": "7 days", "explanation": "1/15 + 1/20 + 1/30 = 9/60. Days = 60/9 ≈ 7", "tags": ["work-time", "hcl"], "year": 2023},
    {"company": "hcl", "category": "logical", "difficulty": "medium", "question_text": "HCL: Missing: 6, 13, 25, 51, 101, ?", "options": ["201", "203", "205", "207"], "correct_answer": "203", "explanation": "Pattern ×2+1, ×2-1 alternating: 101×2+1 = 203", "tags": ["number-series", "hcl"], "year": 2023},
    {"company": "techmahindra", "category": "quantitative", "difficulty": "medium", "question_text": "TechM: Price falls 20%. Consumption increase to maintain same expenditure?", "options": ["20%", "22%", "25%", "30%"], "correct_answer": "25%", "explanation": "20/80 × 100 = 25%", "tags": ["percentages", "techmahindra"], "year": 2023},
    {"company": "techmahindra", "category": "logical", "difficulty": "easy", "question_text": "Tech Mahindra: Odd one out: Pen, Pencil, Paper, Book, Rubber", "options": ["Pen", "Pencil", "Book", "Rubber"], "correct_answer": "Book", "explanation": "Book is not a writing instrument", "tags": ["odd-one-out", "techmahindra"], "year": 2022},
]


def seed_database():
    create_tables()
    db = SessionLocal()
    try:
        existing_q = db.query(Question).count()
        existing_c = db.query(CompanyQuestion).count()

        if existing_q == 0:
            all_q = QUANT + LOGICAL + CODING
            for q in all_q:
                db.add(Question(**q))
            db.commit()
            print(f"✅ Seeded {len(all_q)} questions")
        else:
            print(f"Questions already seeded ({existing_q})")

        if existing_c == 0:
            for q in COMPANY_QUESTIONS:
                db.add(CompanyQuestion(**q))
            db.commit()
            print(f"✅ Seeded {len(COMPANY_QUESTIONS)} company questions")
        else:
            print(f"Company questions already seeded ({existing_c})")

    except Exception as e:
        print(f"Seed error: {e}")
        import traceback
        traceback.print_exc()
        db.rollback()
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
